"""Create Post, Post1, Users Table

Revision ID: 4e0e794faa87
Revises: 
Create Date: 2025-05-14 13:36:52.201119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0e794faa87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_posts_uid'), 'posts', ['uid'], unique=False)
    op.create_table('posts1',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_posts1_uid'), 'posts1', ['uid'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_posts1_uid'), table_name='posts1')
    op.drop_table('posts1')
    op.drop_index(op.f('ix_posts_uid'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
