"""Create Post, Post1, Users Table

Revision ID: 9e14e8855725
Revises: 4e0e794faa87
Create Date: 2025-05-14 18:41:37.655195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e14e8855725'
down_revision: Union[str, None] = '4e0e794faa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts1',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_posts1_uid'), 'posts1', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts1_uid'), table_name='posts1')
    op.drop_table('posts1')
    # ### end Alembic commands ###
